### ISSUE TITLE
Different between this and Zwave2MqTT

### ISSUE THREAD

**Issue by johntdyer** [cgarwood/python-openzwave-mqtt#13]
hey,  super excited to hear about this effort during the state of the union but I have a few questions..  What is the difference between this and The Zwave2MQTT project in the ZWave github org?

**Comment by cgarwood** [comment]
This uses a different MQTT system written by the OpenZWave core developer, @Fishwaldo and should maintain closer support with OpenZWave core updates. I believe a new OpenZWave Control Panel is in the works by the OpenZWave team that will also leveraging this new OpenZWave/MQTT API

**Comment by johntdyer** [comment]
Sounds exciting !

**Comment by balloob** [comment]
The big difference is that this is a library to consume MQTT messages, while Zwave2MQTT produces messages.
