### ISSUE TITLE
Add node.has_command_class helper function

### ISSUE THREAD

**Issue by cgarwood** [cgarwood/python-openzwave-mqtt#40]
Add helper function to test if a node has a specific child command class. Specified by either OZWCommandClass.command_class_id or OZWCommandClass.command_class

Example usage:
```
if node.has_command_class("COMMAND_CLASS_COLOR"):
    # color changing bulb
else:
    # dimming bulb
```

**Comment by marcelveldt** [comment]
This will be a bit tricky to include as values are coming in async and you do not know beforehand which values will be there. In an ideal world all values are loaded so you can do this check very easy (just enumerate the node's CC's and/or values).

This will lead to errors if such a query is done before all values are loaded in. @MartinHjelmare knows all about this when he tried to add the color support to the light platform ;-)

There is one thing however that we could explore and that is to signal initial load: all retained messages loaded ad start/load. Not sure if that is even possible though.

**Comment by marcelveldt** [comment]
I had a better look and we're in luck as queuing all child messages is already implemented.
So this might actually work for retained messages. It won't work however when a new node comes in but as that's an event too you might even work around that.

**Comment by marcelveldt** [comment]
this one is implemented
