### ISSUE TITLE
Radio Thermostat RTZW-01 temperature unit

### ISSUE THREAD

**Issue by balloob** [cgarwood/python-openzwave-mqtt#52]
The Radio Thermostat RTZW-01 z-wave module only reports temperatures in Farenheit but I use Celsius units. When added to home-assistant as an MQTT-hvac component (in conjunction with the new homeassistant-mqtt-zwave component), reported current temperatures and setpoints are displayed in Farenheit with Celsius units.

_Originally posted by @mpbelhorn in https://github.com/home-assistant/home-assistant/issues/30600#issuecomment-590318790_

**Comment by marcelveldt** [comment]
I've seen this issue appear on one of my own sensors too but it disappeared after manually waking up the sensor to let OZW reload it's details. In my case 3 times a press of the pair button.
This workaround should in any way not be handled by this client but upstream in the broker.
