### ISSUE TITLE
Add list value support

### ISSUE THREAD

**Issue by steinerl** [cgarwood/python-openzwave-mqtt#53]
Hello,

given we have a configuration value of type `List`:

```json
{
  "Label": "Roller Shutter operating modes",
  "Value": {
    "List": [
      {
        "Value": 0,
        "Label": "0 - Roller Blind Mode, without positioning"
      },
      {
        "Value": 1,
        "Label": "1 - Roller Blind Mode, with positioning"
      }
    ],
    "Selected": "0 - Roller Blind Mode, without positioning",
    "Selected_id": 0
  },
  "Type": "List",
  "CommandClass": "COMMAND_CLASS_CONFIGURATION",
  "Genre": "Config",
  ...
}
```

When we request the `value` property of class `OZWValue` it returns the whole JSON structure of the `"Value"` attribute instead of returning the value of the `"Selected_id"` attribute.

I don't know if we should just get the `"Selected_id"` value or if we also need all the `"List"` values in the future.
Do you have an idea/preference on how we should handle that?

**Comment by Fishwaldo** [comment]
From OZW Perspective - The entire List is relevent. The Label is good for GUI's etc and the Individual Values' should be used in scripts/comparisions.

The Selected and Selected_id allow you to programically figure out what Option is currently enabled.

**Comment by marcelveldt** [comment]
We need the entire list in the Hass implementation.
