### ISSUE TITLE
Pass "parent" objects to children

### ISSUE THREAD

**Issue by cgarwood** [cgarwood/python-openzwave-mqtt#7]
Making issues for some items on the todo list in case anyone else wants to jump in with some code.
---

If we have an OZWValue object, we need an easy way to get to the OZWNode and OZWInstance objects that the value belongs to. Right now its easy to go from Instance > Node > Value, but not the other way around.

**Comment by Fishwaldo** [comment]
I’m assuming your talking about the python objects that represent values? In the messages we send on OZW, node and instance should be present in the messages. (If not I can add them)

**Comment by balloob** [comment]
This is Python yeah. In MQTT we are able to pull them out of the topic. But right now we don't keep track of who "owns" the object.
