### ISSUE TITLE
Add Node ID to Device information

### ISSUE THREAD

**Issue by foxy82** [cgarwood/python-openzwave-mqtt#73]
Hi,

Can we add the Node ID to device information (https://developers.home-assistant.io/docs/device_registry_index/) as this will make it much easier to work with the devices in Home Assistant if you know the Node number.

I was thinking we could use either identities (as it is a bit like a serial number) or config_entries (as it is sort of config as well). Either way it would then appear on the Device tab with the manafacture info and product type.

**Comment by cgarwood** [comment]
The `identities` and `config_entry` values for the device registry are for internal mapping of entities to devices to integrations, they're not displayed on the frontend.

It's still early, but there is some discussion about a configuration panel for the new component. Once that's in place it should be able to show the node id for a device or entity.

**Comment by cgarwood** [comment]
This has been added and will be in HA 0.114.
