### ISSUE TITLE
Create classes for ZWave Command Classes

### ISSUE THREAD

**Issue by cgarwood** [cgarwood/python-openzwave-mqtt#8]
Making issues for some items on the todo list in case anyone else wants to jump in with some code.
---

We need to make python classes to map to zwave command classes and tie each OZWValue object to its command class class.

Command Class classes should have functions in place for manipulating the value. Example: a class for COMMAND_CLASS_SWITCH_BINARY should expose turn_on and turn_off functions that would send the proper mqtt command

**Comment by balloob** [comment]
I suggest that we start passing initial data to the contructor when instantiating an object, instead of instantiating it and then calling process message. That means we can start having constructors also be functions that return the right class instance.

**Comment by Fishwaldo** [comment]
a few comments:
1) Passing in via constructor.. Please bare in mind that not all CC's have a single ValueID. somewill have several values that make up a single CC. (eg, MultiLevel Dimmer will have value, dim rate, sometimes even dim/brighten valueid's). so not sure if you can do that unless you batch up all the Values before constructing CC's. 

2) I don't know the internals of HA, but I'd actually encourage you to not "reimplement" CC's in the wrapper. Maybe a "generic" container for all Values that belong to a single CC. Reason I say this, is then potentially you are going to have to deal with different capabilities of devices. eg, for the Color CC - is it 3/4/5 channels? does it have cool white and warm white? etc etc. Now I'm sure you will have to at least "put a category" to each Value (or set of Values)... but is it possible to pass the "raw" value as a "category" to HA and let it do its thing rather than reimplementing ~60 or so CC's that currently existing in OZW (and the spec has maybe close to 80 of them in total).

**Comment by Fishwaldo** [comment]
by not implementing CC's in your integration - Hopefully future versions of OZW become less of a "maintenance" burden on you... as I update OZW in the future, add new features or support newer command classes, hopefully HA can just have minimal updates rather than decode back to CC's and maintain them in sync with OZW development pace (fast or slow :))

**Comment by balloob** [comment]
If we don't add it to this lib, would then every consumer of this lib have to figure it out? In that case we're either doing the work ourselves here, or inside HA, so might as well do it here so we also help other consumers of this lib. 

How do we know the type of a command class? We know the ID from the topic, but is there a specific CC info message ?

**Comment by cgarwood** [comment]
The commandclass topic has a payload with the CC ID and name:
```
{
    "Instance": 1,
    "CommandClassId": 37,
    "CommandClass": "COMMAND_CLASS_SWITCH_BINARY",
    "TimeStamp": 1574018439
}
```

On the HA side, we'd then have a list of CCs that make up a `light` or `sensor` etc similar to the discovery_schema in the existing component.

**Comment by Fishwaldo** [comment]
The CC that a value belongs to is also included the payload for each ValueID. So you can infer it from the topic path, or from the ValueID.

>on the HA side, we'd then have a list of CCs that make up a light or sensor etc similar to the discovery_schema in the existing component.

This is where it might get tricky. A SwitchBinary CC could be a light, power outlet, or anything else that has on/off states.... If you want to go "full on mapping" between a ZWave node, you could use the Device Types to infer the function of the device. But its a long, every growing list. Here is a idea of it: https://github.com/OpenZWave/open-zwave/blob/cbe2b60f9470a5552336748719a18390457fc97b/config/device_classes.xml#L276

(we expose that info in the Node Payload)

**Comment by Fishwaldo** [comment]
So I'll put some notes here about some CC that might need some Special Treatment. Lets start with the simple one first:

**SwitchMultiLevel**
Issue: Some devices will respond with a "Instant" value (point in time) when changing the level of a dimmer, and some will respond with the final value.
this was in part to dis-ambiguity on the Specifications. 
What would happen, say the dimmer is set to 0% and a user sets 50%, then, OZW will refresh the values immediately after setting to 50% and the "Level" value may be anywhere between 0% and 50%. Hence GUI's might jump around a bit. (you slide it to 50%, it gets refreshed to 20%, and unless you manually refresh again (or call "setChangedVerified" (pending to be added to qt-openzwave)) then the "Level" value will never get updated with the final value the dimmer ends at.

In 1.6, for devices that support it, the SwitchMultiLevel will export 2 relevant values:
`Level` - the current actual level of the switch
`Target Level` - when a level is changed, this is the final value that the dimmer etc is heading towards
This is only supported on devices that support SwitchMultiLevel Version 4

**Recommendation**:
If present - Test for equality between "Target Level" and "Level" - If they are different then the device is transitioning to a new level. Use "Target Level" as the "display" variable, but actually set "Level" to change Levels.
Or (prefered)
if "Target Level" != "Level" then setChangeVerified("Level")
or (manual?)
if "Target Level" != "Level" then refreshValue("Level")

**Comment by Fishwaldo** [comment]
**UserCode Command Class**
This was re-written in 1.6. It should be a bit simplier to use (in 90% of cases)
Again, early versions of this command class didn't specify how to encode the "code" to the device. Some devices used "ASCII" - Some used "Integers" and some (RFID Tags) went off and did weird things.

In later versions of the specifications, it was clarified that user codes are represented as ASCII. In 1.6 we now export the User Code as a ASCII string by default

3 default values are exposed:
`Code Count` - How many codes are possible on the device. 
`Refresh All UserCodes` - By default, when starting up, OZW will get consecutive codes (starting from position 1) and continue till the first "empty" code. If users have gaps in their codes (eg, Position 1, 4) then we will stop after trying to get Position 2 and see its empty (thus never getting Code 4). "Refresh All Codes" will go from Position 1 to whatever the max number of codes supported. (upto 254!). 
`Remove User Code` - Place the "index" of a usercode you wish to erase into this valueID

Actual UserCodes are by default as ASCII and start to appear at Index position 1 as a String. 

Some devices such as a RFID Tag Reader that can not encode the "tag" as ASCII will also expose a "Raw UserCode" and "Raw UserCode Index". These are encoded as a byte stream. To get the Raw value - setValue the index of the position you are interested in to "Raw UserCode Index" and the "Raw UserCode" valueid will be updated. (but in reality, I don't think users can "display" the raw usercode unless you want to support them inputing a byte stream of the RFID tag.

Note - Index 0 - "Enrollment Code" is reserved for some devices that allow them to set UserCodes on the device themselves. Its Ready Only and for display purposes only.

**Comment by Fishwaldo** [comment]
**Central Scene**

This has been rewritten in 1.6 and supports full discovery of a devices capabilities (in 1.4, users had to hack config files).

`Scene Count` - How many "scenes" the device Supports
`Scene Reset Timeout` - See below

Actual "Scenes" start at Index 1 and are a "Value List". For recent devices, the "List" contains the actual modes the device supports (Pressed 1 time, pressed 2 times etc) plus a special entry "Inactive"

When a user presses a "Scene" Button, the ValueID will update from  "Inactive" to the mode the user did (pressed once, pressed twice etc). 

After "Scene Reset Timeout" OZW will reset the value back to "Inactive" - This allows you to detect changes again in the future. Say the pressed Scene 1 button once, paused and then did it again, it would go "Inactive" - "Pressed once" - "Inactive" - "Pressed Once"

**Comment by Fishwaldo** [comment]
**SensorMultiLevel**

Is Much the same as in previous versions, but a limitation in HA currently is that only "one type of sensor" can be supported per endpoint, but in Z-Wave, you can have multiple types of sensors supported. (eg, two temperature sensors, indoor/outdoor etc)

Lookup Heatit on the community etc to see the "hacks" users had to do to support Multiple Temp Sensors (or get the right sensor they are interested in)

**Comment by cgarwood** [comment]
Going to close this for now, I don't believe classes for everything are needed at this time, and we haven't yet had a need for it in the Home Assistant component
